services:
  bot:
    build: .
    container_name: numora-bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DATABASE_URL=postgresql://postgres:password@db:5432/crime_stats
      - DEBUG=${DEBUG:-False}
      - ADMIN_CHANNEL_ID=${ADMIN_CHANNEL_ID}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models
      - ./backups:/app/backups
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - numora-network

  web:
    build: .
    container_name: numora-web
    command: python -c "from src.utils.web_interface import WebInterface; from src.data.processor import DataProcessor; web = WebInterface(DataProcessor()); web.start_server(host='0.0.0.0', port=5000)"
    ports:
      - "12020:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/crime_stats
      - DEBUG=${DEBUG:-False}
      - CKAN_BASE=${CKAN_BASE:-https://data.taipei/api/3/action}
      - TAIPEI_DATASET_ID=${TAIPEI_DATASET_ID}
      - CKAN_QUERY=${CKAN_QUERY}
      - CKAN_LIMIT=${CKAN_LIMIT:-200}
      - DYNAMIC_DATA_URL=${DYNAMIC_DATA_URL}
      - DATA_REFRESH_MINUTES=${DATA_REFRESH_MINUTES:-0}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models
      - ./templates:/app/templates
      - ./static:/app/static
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - numora-network

  db:
    image: postgres:13
    container_name: numora-db
    environment:
      - POSTGRES_DB=crime_stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "12017:5432"
    restart: unless-stopped
    networks:
      - numora-network

  redis:
    image: redis:6-alpine
    container_name: numora-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "12015:6379"
    restart: unless-stopped
    networks:
      - numora-network

  nginx:
    image: nginx:alpine
    container_name: numora-nginx
    ports:
      - "12019:80"
      - "12013:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - numora-network

volumes:
  postgres_data:
  redis_data:

networks:
  numora-network:
    driver: bridge
